### ISSUE TITLE
won't run on linux?

### ISSUE THREAD

**Issue by alphanumeric0101** [srtucker22/quasar#10]
Any idea what's up there? I use Linux and would be willing to look into it!

**Comment by alphanumeric0101** [comment]
I just read issue #8, let me know if you've got any other info, else I can just starting hacking and see what happens :P

**Comment by srtucker22** [comment]
right now, afaik, meteor-electron doesn't support linux (see https://github.com/electron-webapps/meteor-electron/issues/62), but the rest of the app should work just fine, so if you don't include the electron param in your settings.json file, the app should run without issue. 

in any event, if you want to build the electron app for windows or mac, i suggest running the app from a mac or setting up a virtual machine

let me know how it goes!

**Comment by alphanumeric0101** [comment]
right ok, feel free to close this ticket! If I get time to look at it I'll do so on meteor-electron, cheers.
