### ISSUE TITLE
Application has error

### ISSUE THREAD

**Issue by raz21** [srtucker22/quasar#11]
When we run: > "meteor --settings settings.json" to command line get eorrors:
Errors prevented startup:
While checking for srtucker22:throttled-requester@0.0.1:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

Again when we tried with: "meteor add srtucker22:throttled-requester"  command get errors saying:
While checking for srtucker22:throttled-requester@0.0.1:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

![image](https://cloud.githubusercontent.com/assets/17158804/14315372/497fa08e-fc1a-11e5-8ee9-b7cc804c1f1d.png)

**Comment by srtucker22** [comment]
thanks for this. i need to release the package for windows binaries :/
i'll try and get this out later today. if you need this working right away, you can copy the code out of the [throttled requester repo](https://github.com/srtucker22/throttled-requester), put in your top level packages folder, and everything should work.

**Comment by raz21** [comment]
Thanks for your quick response. I have tried with your instruction by putting codes in top level Package folder but again getting same errors. I would appreciate if you could release the package for windows binaries.
