### ISSUE TITLE
Tried running (on windows) as instructed but...

### ISSUE THREAD

**Issue by sonicviz** [srtucker22/quasar#3]
G:\Meteor Projects\quasar-master\.meteor>meteor
[[[[[ ~\G\Meteor Projects\quasar-master ]]]]]

=> Started proxy.
ERROR: packages.json parsing error [ ENOENT, no such file or directory 'G:\Meteor Projects\quasar-master\.meteor\packages.json' ]
=> Started MongoDB.
=> Errors prevented startup:

   While checking for markoshust:radium@0.1.0:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish
   it for your platform.

=> Your application has errors. Waiting for file change.
Terminate batch job (Y/N)? y

**Comment by srtucker22** [comment]
Thanks for calling this out. Seems like this is an issue with radium that shows up for some people.

Normally, I'd just suggest running <code>meteor update</code> but not today! After running the update, I ran into a related radium issue, all of which is documented in <a href="https://github.com/markoshust/meteor-radium/issues/5">this github issue</a> on the markoshust:radium repo. Seems like I'm not the only one. So, the current workaround is to just make a local radium package with the latest version. 

The latest commit 34a3b13 should fix the issue.
Once you pull the changes run <code>git submodule update --init</code> which should load in radium to the local folder, then try running the app again. <code>meteor --settings settings.json</code>

Once someone figures out the radium issue this extra step will disappear.
 
Let me know how it goes!

**Comment by sonicviz** [comment]
Thanks. It ran this time, but I need to set it. 

Thanks for the quick response and fix.
