### ISSUE TITLE
Electron errors

### ISSUE THREAD

**Issue by mattwkelly** [srtucker22/quasar#8]
I'm trying to get the demo to work, but I'm getting errors when loading the app:

matt@li158-182 ~/www/www.mattwkelly.com/public_html/quasar (master *) $ meteor --settings settings.json
[[[[[ /srv/www/www.mattwkelly.com/public_html/quasar ]]]]]

=> Started proxy.
=> Started MongoDB.
npm-container: updating npm dependencies -- bowser, externalify, react-tagsinput, webrtc-adapter-test...
I20160218-19:04:41.541(-8)? Kadira: successfully authenticated
W20160218-19:04:41.544(-8)? (STDERR) Packaging app for platform darwin x64 using electron v0.36.2
I20160218-19:04:44.570(-8)? Build created for  darwin x64 at /home/matt/www/www.mattwkelly.com/public_html/quasar/.meteor-electron/darwin-x64/builds/quasar-darwin-x64
W20160218-19:04:44.590(-8)? (STDERR)
W20160218-19:04:44.592(-8)? (STDERR) /home/matt/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20160218-19:04:44.592(-8)? (STDERR) 						throw(ex);
W20160218-19:04:44.592(-8)? (STDERR) 						      ^
W20160218-19:04:44.714(-8)? (STDERR) Error: Command failed: /bin/sh: 1: ditto: not found
W20160218-19:04:44.714(-8)? (STDERR)     at Object.Future.wait (/home/matt/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20160218-19:04:44.715(-8)? (STDERR)     at packages/meteor/helpers.js:119:1
W20160218-19:04:44.715(-8)? (STDERR)     at packages/quark_electron/server/createBinaries.js:202:1
W20160218-19:04:44.715(-8)? (STDERR)     at Array.forEach (native)
W20160218-19:04:44.715(-8)? (STDERR)     at createBinaries (packages/quark_electron/server/createBinaries.js:63:1)
W20160218-19:04:44.715(-8)? (STDERR)     at Package (packages/quark_electron/server/index.js:4:1)
W20160218-19:04:44.715(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:759:4
W20160218-19:04:44.716(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:769:3
W20160218-19:04:44.716(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/boot.js:242:10
W20160218-19:04:44.716(-8)? (STDERR)     at Array.forEach (native)
W20160218-19:04:44.716(-8)? (STDERR)     - - - - -
W20160218-19:04:44.716(-8)? (STDERR)
W20160218-19:04:44.716(-8)? (STDERR)     at ChildProcess.exithandler (child_process.js:658:15)
W20160218-19:04:44.716(-8)? (STDERR)     at ChildProcess.emit (events.js:98:17)
W20160218-19:04:44.717(-8)? (STDERR)     at maybeClose (child_process.js:766:16)
W20160218-19:04:44.717(-8)? (STDERR)     at Socket.<anonymous> (child_process.js:979:11)
W20160218-19:04:44.717(-8)? (STDERR)     at Socket.emit (events.js:95:17)
W20160218-19:04:44.717(-8)? (STDERR)     at Pipe.close (net.js:466:12)
=> Exited with code: 8
W20160218-19:04:57.516(-8)? (STDERR)
W20160218-19:04:57.518(-8)? (STDERR) /home/matt/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20160218-19:04:57.518(-8)? (STDERR) 						throw(ex);
W20160218-19:04:57.518(-8)? (STDERR) 						      ^
W20160218-19:04:57.545(-8)? (STDERR) Error: Command failed: /bin/sh: 1: ditto: not found
W20160218-19:04:57.546(-8)? (STDERR)     at Object.Future.wait (/home/matt/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20160218-19:04:57.546(-8)? (STDERR)     at packages/meteor/helpers.js:119:1
W20160218-19:04:57.546(-8)? (STDERR)     at packages/quark_electron/server/createBinaries.js:202:1
W20160218-19:04:57.546(-8)? (STDERR)     at Array.forEach (native)
W20160218-19:04:57.546(-8)? (STDERR)     at createBinaries (packages/quark_electron/server/createBinaries.js:63:1)
W20160218-19:04:57.546(-8)? (STDERR)     at Package (packages/quark_electron/server/index.js:4:1)
W20160218-19:04:57.547(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:759:4
W20160218-19:04:57.547(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:769:3
W20160218-19:04:57.547(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/boot.js:242:10
W20160218-19:04:57.547(-8)? (STDERR)     at Array.forEach (native)
W20160218-19:04:57.547(-8)? (STDERR)     - - - - -
W20160218-19:04:57.547(-8)? (STDERR)
W20160218-19:04:57.548(-8)? (STDERR)     at ChildProcess.exithandler (child_process.js:658:15)
W20160218-19:04:57.548(-8)? (STDERR)     at ChildProcess.emit (events.js:98:17)
W20160218-19:04:57.548(-8)? (STDERR)     at maybeClose (child_process.js:766:16)
W20160218-19:04:57.548(-8)? (STDERR)     at Socket.<anonymous> (child_process.js:979:11)
W20160218-19:04:57.548(-8)? (STDERR)     at Socket.emit (events.js:95:17)
W20160218-19:04:57.548(-8)? (STDERR)     at Pipe.close (net.js:466:12)
=> Exited with code: 8
W20160218-19:05:10.354(-8)? (STDERR)
W20160218-19:05:10.356(-8)? (STDERR) /home/matt/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20160218-19:05:10.356(-8)? (STDERR) 						throw(ex);
W20160218-19:05:10.356(-8)? (STDERR) 						      ^
W20160218-19:05:10.399(-8)? (STDERR) Error: Command failed: /bin/sh: 1: ditto: not found
W20160218-19:05:10.399(-8)? (STDERR)     at Object.Future.wait (/home/matt/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20160218-19:05:10.399(-8)? (STDERR)     at packages/meteor/helpers.js:119:1
W20160218-19:05:10.399(-8)? (STDERR)     at packages/quark_electron/server/createBinaries.js:202:1
W20160218-19:05:10.399(-8)? (STDERR)     at Array.forEach (native)
W20160218-19:05:10.400(-8)? (STDERR)     at createBinaries (packages/quark_electron/server/createBinaries.js:63:1)
W20160218-19:05:10.400(-8)? (STDERR)     at Package (packages/quark_electron/server/index.js:4:1)
W20160218-19:05:10.400(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:759:4
W20160218-19:05:10.400(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:769:3
W20160218-19:05:10.400(-8)? (STDERR)     at /srv/www/www.mattwkelly.com/public_html/quasar/.meteor/local/build/programs/server/boot.js:242:10
W20160218-19:05:10.400(-8)? (STDERR)     at Array.forEach (native)
W20160218-19:05:10.401(-8)? (STDERR)     - - - - -
W20160218-19:05:10.401(-8)? (STDERR)
W20160218-19:05:10.401(-8)? (STDERR)     at ChildProcess.exithandler (child_process.js:658:15)
W20160218-19:05:10.401(-8)? (STDERR)     at ChildProcess.emit (events.js:98:17)
W20160218-19:05:10.401(-8)? (STDERR)     at maybeClose (child_process.js:766:16)
W20160218-19:05:10.402(-8)? (STDERR)     at Socket.<anonymous> (child_process.js:979:11)
W20160218-19:05:10.402(-8)? (STDERR)     at Socket.emit (events.js:95:17)
W20160218-19:05:10.402(-8)? (STDERR)     at Pipe.close (net.js:466:12)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by mattwkelly** [comment]
Another issue: I changed 'autoPackage' in setting.json to false and that allowed the app to launch, but I'm getting a white screen of death. You can see it at http://mattkel.ly:3000/.

**Comment by srtucker22** [comment]
hey @mattwkelly 
you caught me right as I pushed some big changes, so first I would start by pulling those.
for the first issue, it's related to building the electron app --> if you try running 'ditto' on the instance your building on, does it work? what type of machine are you building to? can troubleshoot from there

the second issue --> i see the landing page, but i'm guessing you're talking about when you try and start video? are you getting errors in the console? one quick thing i noticed is you're not using SSL on your server, so chrome and others will block you from sharing video. this latest release should try to force SSL, but you might also have to configure whatever service you're using as well.

let me know if those solve your issues ~ or if you find your own way around them, please contribute. thanks!

**Comment by mattwkelly** [comment]
Thanks for the quick help!

Issue 1: No ditto-- that's the problem (I've never used it, only cp).

Issue 2: WSOD was due to uBlock, it looks like (disabling it and incognito works fine).

Pulling the latest changes now.

**Comment by mattwkelly** [comment]
Also I'm on Ubuntu 14.04, FYI.

**Comment by mattwkelly** [comment]
Hitting a similar but seemingly different issue with the new changes:
W20160218-21:05:53.001(-8)? (STDERR) Packaging app for platform win32 ia32 using electron v0.36.2
W20160218-21:05:55.269(-8)? (STDERR)
W20160218-21:05:55.270(-8)? (STDERR) /home/matt/.meteor/packages/meteor-tool/.1.1.11-cordova.3.51vvrt++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20160218-21:05:55.270(-8)? (STDERR) 						throw(ex);
W20160218-21:05:55.271(-8)? (STDERR) 						      ^
W20160218-21:05:55.378(-8)? (STDERR) Error: spawn ENOTDIR
W20160218-21:05:55.378(-8)? (STDERR)     at Object.Future.wait (/home/matt/.meteor/packages/meteor-tool/.1.1.11-cordova.3.51vvrt++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20160218-21:05:55.378(-8)? (STDERR)     at packages/meteor/helpers.js:119:1
W20160218-21:05:55.378(-8)? (STDERR)     at packages/quark_electron/server/createBinaries.js:183:1
W20160218-21:05:55.379(-8)? (STDERR)     at Array.forEach (native)
W20160218-21:05:55.379(-8)? (STDERR)     at createBinaries (packages/quark_electron/server/createBinaries.js:63:1)
W20160218-21:05:55.379(-8)? (STDERR)     at Package (packages/quark_electron/server/index.js:4:1)
W20160218-21:05:55.379(-8)? (STDERR)     at /srv/www/www.codebounti.es/public_html/instahelp/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:759:4
W20160218-21:05:55.379(-8)? (STDERR)     at /srv/www/www.codebounti.es/public_html/instahelp/quasar/.meteor/local/build/programs/server/packages/quark_electron.js:769:3
W20160218-21:05:55.379(-8)? (STDERR)     at /srv/www/www.codebounti.es/public_html/instahelp/quasar/.meteor/local/build/programs/server/boot.js:245:10
W20160218-21:05:55.379(-8)? (STDERR)     at Array.forEach (native)
W20160218-21:05:55.380(-8)? (STDERR)     - - - - -
W20160218-21:05:55.380(-8)? (STDERR)     at errnoException (child_process.js:1011:11)
W20160218-21:05:55.380(-8)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)

(and it keeps retrying and failing)

I turned autoPackage off and I'm still getting it.

**Comment by mattwkelly** [comment]
I ran just 'meteor' and the server is successful, but it's redirecting me to localhost:3000 (admittedly I'm a meteor newb).

**Comment by srtucker22** [comment]
so quasar relies on the [meteor-electron](https://github.com/electron-webapps/meteor-electron) package to take your app and package it as a native desktop app for windows or mac. the package requires some finagling if you're using a windows machine or if you're trying to build a windows app in mac, and doesn't seem to work at all if you're using linux. to not include the electron feature of quasar, simply remove the entire 'electron' field from your settings.json file -- for example:

```
{
  "google" : {
    "clientId" : "YOUR_CLIENT_ID",
    "clientSecret" : "YOUR_CLIENT_SECRET"
  },
  "public": {
    "analyticsSettings": {
      "Google Analytics": {"trackingId": "YOUR_TRACKING_ID"},
      "Segment.io" : {"apiKey": "YOUR_API_KEY"}
    },
    "google": {
      "browserKey": "YOUR_BROWSER_KEY"
    }
  }
}
```

i can probably update the readme to warn people of the limitations here.

just executing `meteor` will boot up a local server at port 3000. the settings flag will apply the settings to the app for the build. to deploy to an instance, you can use something like [meteor up](https://github.com/arunoda/meteor-up), but to build locally, you can just execute meteor and if you want you can specify the port `meteor -p 4000`

**Comment by mattwkelly** [comment]
Thanks for the details. The readme change might be useful for folks that aren't familiar with meteor/electron (plus maybe you'll get help with the build issues?).

Just the latest changes on my Mac and it's work fine. However, after I pulled your changes to my linode server it's redirecting me to localhost when I go to mattkel.ly:3000 (server is running if you want to check it out-- you can see a 302 in network logs if you preserve logs). Will see what I can dig up, but suggestions welcome.

**Comment by mattwkelly** [comment]
Looks like an issue with ssl (via a force-ssl grep), working on resolving (I think this is just a problem of my lack of knowledge vs a bug).

**Comment by mattwkelly** [comment]
Feel free to ignore this-- apparently mup includes ssl so I'll try that. If it works, I'll make some suggested edits for the README. :)

**Comment by mattwkelly** [comment]
Everything is working now, thanks again for the help. I ended up setting up an nginx proxy for ssl (http://joshowens.me/ssl-and-meteor-js/) and it's working fine now. You might consider adding a call out in the README that mup or something similar should be used when deploying remotely.

**Comment by srtucker22** [comment]
glad it's working. i'll add a line in the docs for remote deploy. 

going to close this ticket for now, but feel free to reopen if similar issues rear their head again

keep me posted on your plans for using. feature requests welcome!
